language: ruby
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
before_install: gem install bundler
script:
- bundle exec rspec
- bundle exec rubocop
addons:
  code_climate:
    repo_token: 5594e3f1541606356c57f9e1921f18506f63696bf118fbc3a5f57d630fe7affe
after_success:
- bundle exec codeclimate-test-reporter
notifications:
  email: false
  slack:
    secure: LE5s1FN+qDXtnaOcIE+WUiKTiu0/Fj+9gfYUyidAUYXHGoXVeFKrw9n0iq5guzZFRROIG1KQUs9TFoRAuQXiy4QLkEmNG+KAXU6OqCDFI40+BPp1I3N9o4FXx2zSCApKwL6f7f9aEiLv1MS181UlLljnAlzrGu9+TdHYgnWJBLnFXHkW6lEpxmvm65ckPragZIj3Fvr4AY+flAUhYGNUX/3tkDH47NtkbzAmox8OJJxCpiczlFLLyMoJY+VEQUBn0QOg67BrBJ4Es9DU2RqJOetqOu9qTdm8NA8hGiL86HFtOrlgZFe8dguGk5cVoFPtkPJF+Rrx1s1wnvCDdDZQeP42sLUZFP54BqBwijy0gxAXG4KDbu613aypK6IWpBKsySriz+PGgpOfsKBCKfFZDZ2v28uSmivzW0g2arXKY0kNeZFHqByKEUWC56qeez6+XexQEBPm7h9Ci0jH6Du2WFOXj/kc2ZPuREEBTvHgmfmU++f51oZ5+98EIk0Rn/gvVrDF4jOHbwE8PnvULlocc4Q+YYMujeLTu4O3a9gDEtc7oPjCQhv7pnOA7IIdXfFxXNOrgILi/aq7PKFJZLHCOlTXtn/sGQufrT6kcZki4s+/dIvbZ+WaHx9MhichBoxWXXrZPrBj0He3ZwZOtGBxukkxnRCPVOoscRnm+aR+G60=
